
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: configure & run cmake
      run: |
        cmake -Bbuild -DCMAKE_CXX_FLAGS="-fopenmp -fprofile-arcs -ftest-coverage"
        cmake --build build --config $BUILD_TYPE -j4

    - name: run tests
      run: |
        cd ${{github.workspace}}/build
        ctest -C $BUILD_TYPE -VV
    
    - name: install & run lcov
      run: | 
        sudo apt-get update && sudo apt-get install -y lcov
        cd ${{github.workspace}}
        lcov --no-external --capture --directory . --ignore mismatch --rc geninfo_unexecuted_blocks=1 --ignore-errors inconsistent --output-file coverage.info

    - name: push on codecov
      uses: codecov/codecov-action@v4
      with:
        files: ${{github.workspace}}/coverage.info
        fail_ci_if_error: true
        verbose: true