
# check cmake-format and cmake-format on pull requests and pushes
name: clang-tidy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: '.clang-format'     # Use .clang-format config file
          tidy-checks: '.clang-tidy' # Use .clang-tidy   config file
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }} # only 'update' a single comment in a pull request thread.
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1